[package]
name = ""
description = ""
edition = "2024"
version = "0.1.0"

authors = ["David Cuthbert <dacut@kanga.org>"]
homepage = "https://github.com/dacut/"
license = "Apache-2.0"
repository = "https://github.com/dacut/.git"

[dependencies]
